[package]
name = "dactyl-db-macros"
version = "0.1.3"
edition = "2021"
rust-version = "1.75"
license = "MIT"
repository = "https://github.com/DecapodLabs/dactyl"
description = "Proc macros for dactyl-db. Implements the `query!` compile-time analyzer."

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
